# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title:       'Blogging my life'
email:       'ngothixuan.apc7@gmail.com'
description: 'Blogging my life'
baseurl:     ''
url:         'https://ngo-xuan.github.io/'
instagram:   'https://www.instagram.com/Im.xuan.ngo/'
facebook:    'https://www.facebook.com/comet.mic'

theme: jekyll-theme-cayman
markdown:  kramdown
permalink: pretty
paginate:  10

sass:
  style: compressed

plugins:
  - jekyll-paginate
  - jekyll/tagging

include:
  - _pages

exclude:
  - vendor
  - Gemfile
  - Gemfile.lock

# Tags
tag_page_dir:         tag
tag_page_layout:      tag_page
tag_permalink_style:  pretty

# Pages path
defaults:
  - scope:
      path: '_pages'
    values:
      permalink: /:basename:output_ext